// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCUolCYUmRpaWV3CtB__o0NLE5auk-STs',
    appId: '1:405433501328:web:d8f436996b9811625aba15',
    messagingSenderId: '405433501328',
    projectId: 'ramadan-appp',
    authDomain: 'ramadan-appp.firebaseapp.com',
    storageBucket: 'ramadan-appp.firebasestorage.app',
    measurementId: 'G-6LPN7YJLK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEInPPjkgsaG49zStbs5DsT9AZEGEKr9Q',
    appId: '1:405433501328:android:723ae6a5f8d09d785aba15',
    messagingSenderId: '405433501328',
    projectId: 'ramadan-appp',
    storageBucket: 'ramadan-appp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi0LIslTq5w-ou7DGj3bg6YEWnFlpfoHo',
    appId: '1:405433501328:ios:1c2ba7c1f8761e635aba15',
    messagingSenderId: '405433501328',
    projectId: 'ramadan-appp',
    storageBucket: 'ramadan-appp.firebasestorage.app',
    iosBundleId: 'com.example.ramadanAppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi0LIslTq5w-ou7DGj3bg6YEWnFlpfoHo',
    appId: '1:405433501328:ios:1c2ba7c1f8761e635aba15',
    messagingSenderId: '405433501328',
    projectId: 'ramadan-appp',
    storageBucket: 'ramadan-appp.firebasestorage.app',
    iosBundleId: 'com.example.ramadanAppp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCUolCYUmRpaWV3CtB__o0NLE5auk-STs',
    appId: '1:405433501328:web:7318343987b12b3b5aba15',
    messagingSenderId: '405433501328',
    projectId: 'ramadan-appp',
    authDomain: 'ramadan-appp.firebaseapp.com',
    storageBucket: 'ramadan-appp.firebasestorage.app',
    measurementId: 'G-SCM00KWG1F',
  );

}